site_name: tfm-clustering
site_description: Caracterización de equipos informáticos mediante clustering en una red empresarial
repo_url: https://github.com/jartigag/tfm-clustering
edit_uri: edit/master/docs/docs
copyright: Project maintained by <a target=_blanks href="https://github.com/jartigag">@jartigag</a>.
theme: cinder
extra_css:
  - css/extra.css
nav:
  - Home: index.md
